@url=http://localhost:5048/api/user


### Register Endpoint
POST {{url}}/register
Content-Type: application/json

{
  "Name": "John Doe",
  "Email": "john.doe@example.com",
  "Password": "SecurePassword123!"
}


### Login Endpoint
POST {{url}}/login
Content-Type: application/json

{
  "Email": "bart@example.com",
  "Password": "Pa$$w0rd"
}