@url=http://localhost:5048/api/course
@courseId=e1dd25b2-60a2-42c4-893e-c580c6abb65c
@lessonId=5e8d583f-23f0-4c13-af3a-0ca0e90860c5
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4YWU2YWNjNS00YWExLTRjMzMtYTAwNS03Y2M0MmQ0YThkNDQiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJ1bmlxdWVfbmFtZSI6IkpvaG4iLCJuYmYiOjE3NDMxNTUzNTAsImV4cCI6MTc0MzE3MzM1MCwiaWF0IjoxNzQzMTU1MzUwLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMTAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.HSTcsIL44IZO1pbvzgqxypuoMMwoC4AqpAftapjUiy8
@creatorId=8ae6acc5-4aa1-4c33-a005-7cc42d4a8d44




### Get Courses Endpoint
GET {{url}}
Content-Type: application/json


### Get Basic Course Endpoint
GET {{url}}/{{courseId}}
Content-Type: application/json


### Get Full Course Endpoint
GET {{url}}/full-course/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Get Enrolled Courses Endpoint 
GET {{url}}/student/my-courses
Authorization: Bearer {{token}}
Content-Type: application/json


### Get Created Course Endpoint
GET {{url}}/instructor/my-courses
Authorization: Bearer {{token}}
Content-Type: application/json


### ----------------------------------


### Add Course Endpoint
POST {{url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "creatorId": "{{creatorId}}",
  "title": "Introduction to Machine Learning",
  "description": "A beginner-friendly course on the fundamentals of machine learning."
}


### Update Course Endpoint
PATCH  {{url}}/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "{{courseId}}",
  "creatorId": "{{creatorId}}",
  "title": "Introduction to Machine Learning 3",
  "description": "A beginner-friendly course on the fundamentals of machine learning."
}


### Delete Course Endpoint
DELETE  {{url}}/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Add Enrollment Endpoint
POST {{url}}/enroll/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Delete Enrollment Endpoint
DELETE  {{url}}/unenroll/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json



