@url=http://localhost:5048/api/v1/courses

@courseId=a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1
@creatorId=33333333-3333-3333-3333-333333333333

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzMzMzMzMzMy0zMzMzLTMzMzMtMzMzMy0zMzMzMzMzMzMzMzMiLCJlbWFpbCI6ImJhcnRAZXhhbXBsZS5jb20iLCJ1bmlxdWVfbmFtZSI6IkJhcnQiLCJuYmYiOjE3NDM0MjkzNzUsImV4cCI6MTc0MzQ0NzM3NSwiaWF0IjoxNzQzNDI5Mzc1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMTAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.wlbe3byTb2aaC_dnIpOn2CJIiE16AFrNyJlFkUE-Ojk





### Get Courses Endpoint
GET {{url}}
Content-Type: application/json


### Get Course (Not Auth) Endpoint
GET {{url}}/{{courseId}}
Content-Type: application/json


### Get Course (Auth) Endpoint
GET {{url}}/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### ----------------------------------


### Add Course Endpoint
POST {{url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "creatorId": "{{creatorId}}",
  "title": "Introduction to Machine Learning",
  "description": "A beginner-friendly course on the fundamentals of machine learning."
}


### Update Course Endpoint
PATCH  {{url}}/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "{{courseId}}",
  "creatorId": "{{creatorId}}",
  "title": "Introduction to Machine Learning 3",
  "description": "A beginner-friendly course on the fundamentals of machine learning."
}


### Delete Course Endpoint
DELETE  {{url}}/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Add Enrollment Endpoint
POST {{url}}/{{courseId}}/enrollments
Authorization: Bearer {{token}}
Content-Type: application/json

### Delete Enrollment Endpoint
DELETE  {{url}}/{{courseId}}/enrollments
Authorization: Bearer {{token}}
Content-Type: application/json


