@url=http://localhost:5048/api/user
@courseId=e1dd25b2-60a2-42c4-893e-c580c6abb65c
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4YWU2YWNjNS00YWExLTRjMzMtYTAwNS03Y2M0MmQ0YThkNDQiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJ1bmlxdWVfbmFtZSI6IkpvaG4iLCJuYmYiOjE3NDMxNTUzNTAsImV4cCI6MTc0MzE3MzM1MCwiaWF0IjoxNzQzMTU1MzUwLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMTAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.HSTcsIL44IZO1pbvzgqxypuoMMwoC4AqpAftapjUiy8


### Add Enrollment Endpoint
POST {{url}}/enroll/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Delete Enrollment Endpoint
DELETE  {{url}}/unenroll/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json