@courseId=a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1
@lessonId=39def555-b92d-4043-b6e1-08dd705ae10d
@url=http://localhost:5048/api/v1/courses/"{{courseId}}"/lessons
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJ1bmlxdWVfbmFtZSI6IkpvaG4iLCJuYmYiOjE3NDM0Mjg5MDksImV4cCI6MTc0MzQ0NjkwOSwiaWF0IjoxNzQzNDI4OTA5LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMTAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.tox4JW6JhggKEOJq2unHpGk-cPaeJrMMElkkOfFfShI
@userId=11111111-1111-1111-1111-111111111111


### Add Progress Endpoint
POST {{url}}/{{lessonId}}/progress
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "UserId": "{{userId}}",
  "LessonId": "{{lessonId}}"
}


### Add Lesson Endpoint
POST {{url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "CourseId": "{{courseId}}",
    "Title": "Example Lesson",
    "Description": "This is an example lesson.",
    "VideoUrl": "https://example.com/video.mp4"
}


### Update Lesson Endpoint
PATCH  {{url}}/{{lessonId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Id": "{{lessonId}}",
    "CourseId": "{{courseId}}",
    "Title": "Example Lesson 2",
    "Description": "This is an example lesson.",
    "VideoUrl": "https://example.com/video.mp4"
}


### Delete Lesson Endpoint
DELETE  {{url}}/{{lessonId}}
Authorization: Bearer {{token}}
Content-Type: application/json



