// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineLearningPlatform.Infrastructure.Database;

#nullable disable

namespace OnlineLearningPlatform.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2020690e-f61d-4093-8832-8b1097665fa0"),
                            CreatedAt = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("36edcfd5-ba02-4144-9850-3a2b390c53e4"),
                            Description = "A comprehensive course covering the basics of C# programming language, including syntax, data types, and object-oriented concepts.",
                            Title = "Introduction to C# Programming"
                        },
                        new
                        {
                            Id = new Guid("222a68ba-ef6d-4efd-b4b2-671eea2b89a5"),
                            CreatedAt = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("36edcfd5-ba02-4144-9850-3a2b390c53e4"),
                            Description = "An in-depth guide to working with Entity Framework Core, covering migrations, relationships, and performance optimization.",
                            Title = "Mastering Entity Framework Core"
                        },
                        new
                        {
                            Id = new Guid("015a803a-57d8-4746-8f49-b89721371342"),
                            CreatedAt = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("36edcfd5-ba02-4144-9850-3a2b390c53e4"),
                            Description = "Learn how to design and develop robust REST APIs using ASP.NET Core, covering controllers, authentication, and best practices.",
                            Title = "Building RESTful APIs with ASP.NET Core"
                        },
                        new
                        {
                            Id = new Guid("c4fad3c9-2447-4801-bfd1-c205624feaed"),
                            CreatedAt = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("36edcfd5-ba02-4144-9850-3a2b390c53e4"),
                            Description = "A hands-on course focused on writing effective unit tests in .NET using xUnit, Moq, and Test-Driven Development (TDD) principles.",
                            Title = "Unit Testing in .NET"
                        });
                });

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e2edfb3-b191-4eb0-a283-29d25084d395"),
                            CourseId = new Guid("2020690e-f61d-4093-8832-8b1097665fa0"),
                            EnrolledAt = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00dbcaf4-95f1-425a-857e-101730edea70")
                        });
                });

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb0c4c0b-6138-4209-9a1b-e616dd0a4eaa"),
                            CourseId = new Guid("2020690e-f61d-4093-8832-8b1097665fa0"),
                            Description = "Installation and setup of development environment.",
                            Title = "Getting Started with C#",
                            VideoUrl = "https://www.youtube.com/watch?v=ravLFzIguCM"
                        },
                        new
                        {
                            Id = new Guid("df89891c-59ca-48a2-8a06-1e52823bf6c3"),
                            CourseId = new Guid("2020690e-f61d-4093-8832-8b1097665fa0"),
                            Description = "Understanding variables and different data types in C#.",
                            Title = "Variables and Data Types",
                            VideoUrl = "https://www.youtube.com/watch?v=_D-HCF3jZKk"
                        },
                        new
                        {
                            Id = new Guid("62099240-e2d7-498a-bf61-53b4ddb2a8df"),
                            CourseId = new Guid("2020690e-f61d-4093-8832-8b1097665fa0"),
                            Description = "Learn about arithmetic, logical, and comparison operators in C#.",
                            Title = "Operators and Expressions",
                            VideoUrl = "https://www.youtube.com/watch?v=WL7QEhdqh00"
                        },
                        new
                        {
                            Id = new Guid("b2ad1223-276e-4456-8417-aea0099ccb0b"),
                            CourseId = new Guid("222a68ba-ef6d-4efd-b4b2-671eea2b89a5"),
                            Description = "Overview of EF Core and setting up the DbContext.",
                            Title = "Introduction to Entity Framework Core",
                            VideoUrl = "https://www.youtube.com/watch?v=KcFWOMbGJ4M"
                        },
                        new
                        {
                            Id = new Guid("6511c33a-ac65-429d-8a30-ebe77496bdd5"),
                            CourseId = new Guid("222a68ba-ef6d-4efd-b4b2-671eea2b89a5"),
                            Description = "How to create and apply migrations in EF Core.",
                            Title = "Working with Migrations",
                            VideoUrl = "https://www.youtube.com/watch?v=ZoKRFVBsm7E"
                        },
                        new
                        {
                            Id = new Guid("1cd7665c-2550-4c2c-b5b2-e1b12103ac2a"),
                            CourseId = new Guid("222a68ba-ef6d-4efd-b4b2-671eea2b89a5"),
                            Description = "Learn how to use LINQ queries in EF Core to fetch data.",
                            Title = "Querying Data with LINQ",
                            VideoUrl = "https://www.youtube.com/watch?v=DuozyaJQQ1U"
                        },
                        new
                        {
                            Id = new Guid("f46f18df-66ca-43b4-9f76-97b915d765c6"),
                            CourseId = new Guid("015a803a-57d8-4746-8f49-b89721371342"),
                            Description = "Understanding controllers, routing, and API responses.",
                            Title = "Building RESTful APIs with ASP.NET Core",
                            VideoUrl = "https://www.youtube.com/watch?v=JiJeZOHx0ow"
                        },
                        new
                        {
                            Id = new Guid("c0b01fde-4295-4569-a1d3-64940486af83"),
                            CourseId = new Guid("015a803a-57d8-4746-8f49-b89721371342"),
                            Description = "Implementing authentication and role-based authorization in ASP.NET Core.",
                            Title = "Authentication and Authorization",
                            VideoUrl = "https://www.youtube.com/watch?v=eUW2CYAT1Nk"
                        });
                });

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.Progress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastWatchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("Progresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f008e742-bdba-4f31-bd35-2ce8c7c0d90b"),
                            LastWatchedAt = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LessonId = new Guid("cb0c4c0b-6138-4209-9a1b-e616dd0a4eaa"),
                            UserId = new Guid("00dbcaf4-95f1-425a-857e-101730edea70")
                        },
                        new
                        {
                            Id = new Guid("4420877e-a7e1-4228-9e3c-b7bace465b03"),
                            LastWatchedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LessonId = new Guid("df89891c-59ca-48a2-8a06-1e52823bf6c3"),
                            UserId = new Guid("00dbcaf4-95f1-425a-857e-101730edea70")
                        },
                        new
                        {
                            Id = new Guid("83faecf7-f987-433a-b37e-7c179707e899"),
                            LastWatchedAt = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LessonId = new Guid("cb0c4c0b-6138-4209-9a1b-e616dd0a4eaa"),
                            UserId = new Guid("555f610b-1169-4bfc-ae8b-3af123f7b480")
                        });
                });

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36edcfd5-ba02-4144-9850-3a2b390c53e4"),
                            Email = "john@example.com",
                            Name = "John",
                            Password = "ol7P+JWmNfXtag31+7OW58hUXbIXMvJm4eFqmepOqbesGfnKytuRXpMeGXyZnPIZDYLSBnrjfzWlkPu4MVPtrw=="
                        },
                        new
                        {
                            Id = new Guid("00dbcaf4-95f1-425a-857e-101730edea70"),
                            Email = "sarah@example.com",
                            Name = "Sarah",
                            Password = "ol7P+JWmNfXtag31+7OW58hUXbIXMvJm4eFqmepOqbesGfnKytuRXpMeGXyZnPIZDYLSBnrjfzWlkPu4MVPtrw=="
                        },
                        new
                        {
                            Id = new Guid("555f610b-1169-4bfc-ae8b-3af123f7b480"),
                            Email = "bart@example.com",
                            Name = "Bart",
                            Password = "ol7P+JWmNfXtag31+7OW58hUXbIXMvJm4eFqmepOqbesGfnKytuRXpMeGXyZnPIZDYLSBnrjfzWlkPu4MVPtrw=="
                        });
                });

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.Course", b =>
                {
                    b.HasOne("OnlineLearningPlatform.Domain.Entities.User", "Creator")
                        .WithMany("CreatedCourses")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("OnlineLearningPlatform.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatform.Domain.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("OnlineLearningPlatform.Domain.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.Progress", b =>
                {
                    b.HasOne("OnlineLearningPlatform.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Progresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatform.Domain.Entities.User", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("OnlineLearningPlatform.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedCourses");

                    b.Navigation("Enrollments");

                    b.Navigation("Progresses");
                });
#pragma warning restore 612, 618
        }
    }
}
