@url=http://localhost:5048/api/v1/auth
@johnEmail=john@example.com
@sarahEmail=sarah@example.com
@bartEmail=bart@example.com

### Register Endpoint
POST {{url}}/register
Content-Type: application/json

{
  "Name": "John Doe",
  "Email": "john.doe@example.com",
  "Password": "SecurePassword123!"
}


### Login Endpoint
POST {{url}}/login
Content-Type: application/json

{
  "Email": "{{sarahEmail}}",
  "Password": "Pa$$w0rd"
}