@url=http://localhost:5048/api/course
@courseId=dc4ca92b-55df-43aa-82a1-08dd6d41a6b5
@lessonId=5e8d583f-23f0-4c13-af3a-0ca0e90860c5
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwMGRiY2FmNC05NWYxLTQyNWEtODU3ZS0xMDE3MzBlZGVhNzAiLCJlbWFpbCI6InNhcmFoQGV4YW1wbGUuY29tIiwidW5pcXVlX25hbWUiOiJTYXJhaCIsIm5iZiI6MTc0MzA4NjA5OSwiZXhwIjoxNzQzMTA0MDk5LCJpYXQiOjE3NDMwODYwOTksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAxMCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDIwMCJ9.T9fOqy7NXs4p16pMq4kKM8_fGZxoSXSn3w6-mDXPQ20
@creatorId=00dbcaf4-95f1-425a-857e-101730edea70




### Get Courses Endpoint
GET {{url}}
Content-Type: application/json


### Get Basic Course Endpoint
GET {{url}}/{{courseId}}
Content-Type: application/json


### Get Full Course Endpoint
GET {{url}}/full-course/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Get Enrolled Courses Endpoint 
GET {{url}}/student/my-courses
Authorization: Bearer {{token}}
Content-Type: application/json


### Get Created Course Endpoint
GET {{url}}/instructor/my-courses
Authorization: Bearer {{token}}
Content-Type: application/json


### ----------------------------------


### Add Course Endpoint
POST {{url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "creatorId": "{{creatorId}}",
  "title": "Introduction to Machine Learning",
  "description": "A beginner-friendly course on the fundamentals of machine learning."
}


### Update Course Endpoint
PATCH  {{url}}/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "{{courseId}}",
  "creatorId": "{{creatorId}}",
  "title": "Introduction to Machine Learning 2",
  "description": "A beginner-friendly course on the fundamentals of machine learning."
}


### Delete Course Endpoint
DELETE  {{url}}/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Add Enrollment Endpoint
POST {{url}}/enroll/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Delete Enrollment Endpoint
DELETE  {{url}}/unenroll/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json



