@url=http://localhost:5048/api/v1/courses
@url2=http://localhost:5048/api/v1/users
@courseId=ef0c94df-ff57-48e7-9073-311d66747dc4
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyMjIyMjIyMi0yMjIyLTIyMjItMjIyMi0yMjIyMjIyMjIyMjIiLCJlbWFpbCI6InNhcmFoQGV4YW1wbGUuY29tIiwidW5pcXVlX25hbWUiOiJTYXJhaCIsIm5iZiI6MTc0NDI3MTQ4OSwiZXhwIjoxNzQ0Mjg5NDg5LCJpYXQiOjE3NDQyNzE0ODksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAxMCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDIwMCJ9.cAAaQhzVPeCS65I80HIjf34hqHCpYs-x0wQVQA59tyQ



@creatorId=22222222-2222-2222-2222-222222222222



### (UnauthorizedAccessException) Unauthorized update (not creator)
PATCH {{url}}/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "{{courseId}}",
  "creatorId": "{{creatorId}}",  
  "title": "Hacked Title",
  "description": "Oops"
}


### (ForbiddenException) Unenroll from a course you're not enrolled in
DELETE  {{url2}}/00000000-0000-0000-0000-000000000000/enrollments/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### (KeyNotFoundException) Get a non-existent course
GET {{url}}/00000000-0000-0000-0000-000000000000
Authorization: Bearer {{token}}
Content-Type: application/json


### (ValidationException) Create course with missing title (validation error)
POST {{url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "creatorId": "{{creatorId}}",
  "title": "Intro to FluentValidation",
  "description": "Fine"
}
